
export const theme = {
  gold: '#66C0F4', // Steam Bright Steel Blue / Cyber Cyan (replaces traditional gold)
  darkGold: '#2A475E', // Steam Slate Steel (replaces dark gold)
  bg: '#171A21', // Steam Deep Body Charcoal Background
  text: '#D6E2EB', // Steam Crisp Silver-Blue text
  panel: 'rgba(23, 38, 54, 0.9)', // Steam Slate-Blue Glass Card Panel
  accent: '#00FFD0', // Steam Vibrant Cyber Mint / Teal Accent Glow
  paper: '#1B2838', // Steam Dark Blue secondary background
};

export const styles = {
  appContainer: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column' as const,
    background: 'radial-gradient(circle at 50% 30%, #1B2838 0%, #171A21 100%)',
    color: theme.text,
    fontFamily: '"Space Grotesk", "Inter", system-ui, sans-serif',
  },
  navbar: {
    background: 'rgba(23, 38, 54, 0.95)',
    borderBottom: `1px solid rgba(102, 192, 244, 0.25)`,
    position: 'sticky' as const,
    top: 0,
    zIndex: 1000,
    backdropFilter: 'blur(12px)',
    boxShadow: '0 4px 30px rgba(0,0,0,0.8)',
  },
  logo: {
    fontFamily: 'Space Grotesk, sans-serif',
    fontSize: '1.6rem',
    fontWeight: '700',
    color: theme.gold,
    textDecoration: 'none',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    cursor: 'pointer',
    textShadow: '0 0 12px rgba(102, 192, 244, 0.5)',
  },
  navLink: {
    color: '#89A2B6', // Muted steel blue
    textDecoration: 'none',
    fontSize: '0.9rem',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'all 0.3s',
    textTransform: 'uppercase' as const,
    letterSpacing: '1.5px',
    whiteSpace: 'nowrap' as const,
  },
  main: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    position: 'relative' as const,
  },
  heroSection: {
    minHeight: '90vh',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center' as const,
    padding: '2rem 1rem',
    position: 'relative' as const,
  },
  baguaContainer: {
    width: '200px',
    height: '200px',
    marginBottom: '2.5rem',
    animation: 'slowSpin 30s linear infinite',
    filter: 'drop-shadow(0 0 20px rgba(102, 192, 244, 0.45))',
  },
  glassPanel: {
    background: theme.panel,
    backdropFilter: 'blur(20px)',
    border: `1px solid rgba(102, 192, 244, 0.22)`,
    borderRadius: '16px', // Rounded modern cards
    padding: '3rem',
    maxWidth: '1200px',
    width: '90%',
    boxShadow: `0 25px 60px rgba(0, 0, 0, 0.85), inset 0 0 35px rgba(102, 192, 244, 0.05)`,
    transition: 'all 0.3s ease',
    position: 'relative' as const,
    zIndex: 10,
    boxSizing: 'border-box' as const,
  },
  button: {
    background: `linear-gradient(90deg, #47BFFF 0%, #1A44C2 100%)`, // Steam Iconic Blue-Indigo glossy gradient
    border: `1px solid #66C0F4`,
    color: '#FFFFFF',
    padding: '16px 32px',
    fontSize: '1rem',
    fontWeight: '600',
    borderRadius: '12px', // Smooth modern corners
    cursor: 'pointer',
    marginTop: '24px',
    transition: 'all 0.3s',
    fontFamily: '"Space Grotesk", sans-serif',
    textTransform: 'uppercase' as const,
    letterSpacing: '1.5px',
    boxShadow: `0 4px 20px rgba(71, 191, 255, 0.3)`,
    display: 'inline-flex',
    alignItems: 'center',
    gap: '12px',
    justifyContent: 'center',
    minWidth: '260px',
    maxWidth: '100%',
  },
  secondaryButton: {
    background: 'rgba(102, 192, 244, 0.06)',
    border: `1px solid rgba(102, 192, 244, 0.35)`,
    color: '#66C0F4',
    padding: '12px 24px',
    fontSize: '0.9rem',
    borderRadius: '8px',
    cursor: 'pointer',
    marginTop: '12px',
    fontFamily: '"Space Grotesk", sans-serif',
    textTransform: 'uppercase' as const,
    letterSpacing: '1px',
    transition: 'all 0.3s',
  },
  resultContainer: {
    background: 'linear-gradient(135deg, #1B2838 0%, #171A21 100%)',
    backgroundImage: `radial-gradient(circle at 50% 15%, rgba(102, 192, 244, 0.2) 0%, transparent 60%)`,
    color: '#E1EBF2',
    padding: '2.5rem 2rem',
    borderRadius: '16px',
    marginTop: '24px',
    textAlign: 'left' as const,
    boxShadow: '0 25px 60px rgba(0,0,0,0.9), inset 0 0 35px rgba(102, 192, 244, 0.05)',
    fontFamily: '"Space Grotesk", "Inter", sans-serif',
    lineHeight: '1.8',
    position: 'relative' as const,
    border: `1px solid rgba(102, 192, 244, 0.25)`,
    width: '100%',
    boxSizing: 'border-box' as const,
  },
  toolbar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    background: 'rgba(102, 192, 244, 0.05)',
    padding: '10px 20px',
    borderRadius: '8px',
    marginBottom: '1.5rem',
    border: `1px solid rgba(102, 192, 244, 0.2)`,
  },
  input: {
      display: 'none',
  },
  cardInput: {
      width: '100%',
      padding: '12px',
      marginTop: '8px',
      marginBottom: '18px',
      borderRadius: '8px',
      border: `1px solid rgba(102, 192, 244, 0.3)`,
      background: 'rgba(11, 16, 26, 0.8)',
      color: '#66C0F4',
      fontFamily: '"Space Grotesk", sans-serif',
      boxSizing: 'border-box' as const,
  },
  formInput: {
      width: '100%',
      padding: '14px',
      borderRadius: '8px',
      border: `1px solid rgba(102, 192, 244, 0.3)`,
      background: 'rgba(11, 16, 26, 0.85)',
      color: '#ffffff',
      fontSize: '1rem',
      fontFamily: '"Space Grotesk", sans-serif',
      marginBottom: '18px',
      boxSizing: 'border-box' as const,
      outline: 'none',
  },
  footer: {
    padding: '3rem 1rem',
    background: '#171A21',
    borderTop: `1px solid rgba(102, 192, 244, 0.15)`,
    textAlign: 'center' as const,
    color: '#89A2B6',
    fontSize: '0.85rem',
    marginTop: 'auto',
    letterSpacing: '1px',
  }
};
