
export const theme = {
  gold: '#D4AF37', // Classic Gold
  darkGold: '#996515', // Golden Brown
  bg: '#1A1A1A', // Deep Charcoal
  text: '#F5F5DC', // Beige/Cream
  panel: 'rgba(40, 30, 20, 0.95)', // Warm dark panel
  accent: '#800000', // Maroon/Deep Red
  paper: '#FDFBF7', // Vintage Paper
};

export const styles = {
  appContainer: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column' as const,
    background: 'radial-gradient(circle at 50% 50%, #2C1E1E 0%, #0A0A0A 100%)',
    color: theme.text,
    fontFamily: '"Cinzel", "Noto Serif", serif',
  },
  navbar: {
    background: 'rgba(26, 20, 10, 0.95)',
    borderBottom: `2px solid ${theme.gold}`,
    position: 'sticky' as const,
    top: 0,
    zIndex: 1000,
    backdropFilter: 'blur(10px)',
    boxShadow: '0 4px 20px rgba(0,0,0,0.5)',
  },
  logo: {
    fontFamily: 'Cinzel, serif',
    fontSize: '1.8rem',
    fontWeight: '700',
    color: theme.gold,
    textDecoration: 'none',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    cursor: 'pointer',
    textShadow: '0 0 10px rgba(212, 175, 55, 0.5)',
  },
  navLink: {
    color: theme.gold,
    textDecoration: 'none',
    fontSize: '0.95rem',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'all 0.3s',
    textTransform: 'uppercase' as const,
    letterSpacing: '2px',
    whiteSpace: 'nowrap' as const,
  },
  main: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    position: 'relative' as const,
  },
  heroSection: {
    minHeight: '90vh',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center' as const,
    padding: '2rem 1rem',
    position: 'relative' as const,
  },
  baguaContainer: {
    width: '200px',
    height: '200px',
    marginBottom: '2.5rem',
    animation: 'slowSpin 30s linear infinite',
    filter: 'drop-shadow(0 0 15px rgba(212, 175, 55, 0.4))',
  },
  glassPanel: {
    background: theme.panel,
    backdropFilter: 'blur(15px)',
    border: `2px solid ${theme.gold}`,
    borderRadius: '4px', // More traditional sharp corners
    padding: '3rem',
    maxWidth: '1200px',
    width: '90%',
    boxShadow: `0 0 50px rgba(0, 0, 0, 0.8), inset 0 0 20px rgba(212, 175, 55, 0.1)`,
    transition: 'all 0.3s ease',
    position: 'relative' as const,
    zIndex: 10,
    boxSizing: 'border-box' as const,
  },
  button: {
    background: `linear-gradient(180deg, #D4AF37 0%, #996515 100%)`,
    border: `1px solid #F5F5DC`,
    color: '#1A1A1A',
    padding: '16px 32px',
    fontSize: '1.1rem',
    fontWeight: '700',
    borderRadius: '0px', // Sharp vintage look
    cursor: 'pointer',
    marginTop: '24px',
    transition: 'all 0.3s',
    fontFamily: 'Cinzel, serif',
    textTransform: 'uppercase' as const,
    letterSpacing: '2px',
    boxShadow: `0 4px 15px rgba(0, 0, 0, 0.5)`,
    display: 'inline-flex',
    alignItems: 'center',
    gap: '12px',
    justifyContent: 'center',
    minWidth: '260px',
    maxWidth: '100%',
  },
  secondaryButton: {
    background: 'transparent',
    border: `1px solid ${theme.gold}`,
    color: theme.gold,
    padding: '12px 24px',
    fontSize: '0.9rem',
    borderRadius: '0px',
    cursor: 'pointer',
    marginTop: '12px',
    fontFamily: 'Cinzel, serif',
    textTransform: 'uppercase' as const,
    letterSpacing: '1.5px',
    transition: 'all 0.3s',
  },
  resultContainer: {
    background: theme.paper,
    backgroundImage: `url("https://www.transparenttextures.com/patterns/cream-paper.png")`,
    color: '#2C1E1E',
    padding: '3rem',
    borderRadius: '0px',
    marginTop: '24px',
    textAlign: 'left' as const,
    maxHeight: '65vh',
    overflowY: 'auto' as const,
    boxShadow: '0 10px 40px rgba(0,0,0,0.6), inset 0 0 100px rgba(138, 110, 47, 0.15)',
    fontFamily: '"Noto Serif", serif',
    lineHeight: '2',
    position: 'relative' as const,
    border: `3px double ${theme.gold}`,
    width: '100%',
    boxSizing: 'border-box' as const,
  },
  toolbar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    background: 'rgba(212, 175, 55, 0.1)',
    padding: '10px 20px',
    borderRadius: '0px',
    marginBottom: '1.5rem',
    border: `1px solid ${theme.gold}`,
  },
  input: {
      display: 'none',
  },
  cardInput: {
      width: '100%',
      padding: '12px',
      marginTop: '8px',
      marginBottom: '18px',
      borderRadius: '0px',
      border: `1px solid ${theme.gold}`,
      background: 'rgba(0,0,0,0.5)',
      color: theme.gold,
      fontFamily: '"Noto Serif", serif',
      boxSizing: 'border-box' as const,
  },
  formInput: {
      width: '100%',
      padding: '14px',
      borderRadius: '0px',
      border: `1px solid ${theme.gold}`,
      background: 'rgba(0,0,0,0.6)',
      color: theme.gold,
      fontSize: '1.1rem',
      fontFamily: '"Noto Serif", serif',
      marginBottom: '18px',
      boxSizing: 'border-box' as const,
      outline: 'none',
  },
  footer: {
    padding: '3rem 1rem',
    background: 'rgba(10, 10, 10, 0.98)',
    borderTop: `2px solid ${theme.gold}`,
    textAlign: 'center' as const,
    color: theme.gold,
    fontSize: '0.85rem',
    marginTop: 'auto',
    letterSpacing: '1px',
  }
};
