
export const theme = {
  gold: '#d4af37',
  darkGold: '#8a6e2f',
  bg: '#050511',
  text: '#e0e0e0',
  panel: 'rgba(15, 15, 25, 0.85)',
  accent: '#c0392b',
};

export const styles = {
  appContainer: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column' as const,
    background: 'radial-gradient(circle at center, #1a1a2e 0%, #050511 100%)',
    color: theme.text,
    fontFamily: 'Noto Serif, serif',
  },
  navbar: {
    background: 'rgba(5, 5, 17, 0.9)',
    borderBottom: `1px solid ${theme.darkGold}`,
    position: 'sticky' as const,
    top: 0,
    zIndex: 1000,
    backdropFilter: 'blur(10px)',
  },
  logo: {
    fontFamily: 'Cinzel, serif',
    fontSize: '1.5rem',
    fontWeight: 'bold',
    color: theme.gold,
    textDecoration: 'none',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    cursor: 'pointer',
  },
  navLink: {
    color: theme.text,
    textDecoration: 'none',
    fontSize: '0.9rem',
    cursor: 'pointer',
    transition: 'color 0.3s',
    textTransform: 'uppercase' as const,
    letterSpacing: '1px',
    whiteSpace: 'nowrap' as const,
  },
  main: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    position: 'relative' as const,
  },
  heroSection: {
    minHeight: '90vh',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center' as const,
    padding: '2rem 1rem',
    position: 'relative' as const,
  },
  baguaContainer: {
    width: '180px',
    height: '180px',
    marginBottom: '2rem',
    animation: 'slowSpin 60s linear infinite',
  },
  glassPanel: {
    background: theme.panel,
    backdropFilter: 'blur(12px)',
    border: `1px solid ${theme.darkGold}`,
    borderRadius: '16px',
    padding: '2.5rem',
    maxWidth: '1200px',
    width: '90%',
    boxShadow: `0 0 30px rgba(212, 175, 55, 0.15)`,
    transition: 'all 0.3s ease',
    position: 'relative' as const,
    zIndex: 10,
    boxSizing: 'border-box' as const,
  },
  button: {
    background: `linear-gradient(135deg, ${theme.darkGold}, #b8860b)`,
    border: '1px solid #ffd700',
    color: '#050511',
    padding: '14px 28px',
    fontSize: '1rem',
    fontWeight: 'bold',
    borderRadius: '2px',
    cursor: 'pointer',
    marginTop: '20px',
    transition: 'all 0.2s',
    fontFamily: 'Cinzel, serif',
    textTransform: 'uppercase' as const,
    letterSpacing: '1px',
    boxShadow: `0 4px 15px rgba(212, 175, 55, 0.3)`,
    display: 'inline-flex',
    alignItems: 'center',
    gap: '10px',
    justifyContent: 'center',
    minWidth: '240px',
    maxWidth: '100%',
  },
  secondaryButton: {
    background: 'transparent',
    border: `1px solid ${theme.darkGold}`,
    color: theme.darkGold,
    padding: '10px 20px',
    fontSize: '0.9rem',
    borderRadius: '2px',
    cursor: 'pointer',
    marginTop: '10px',
    fontFamily: 'Cinzel, serif',
    textTransform: 'uppercase' as const,
    letterSpacing: '1px',
    transition: 'all 0.2s',
  },
  resultContainer: {
    background: '#fdfbf7',
    backgroundImage: `url("https://www.transparenttextures.com/patterns/cream-paper.png")`,
    color: '#2c1e1e',
    padding: '2rem 2rem',
    borderRadius: '2px',
    marginTop: '20px',
    textAlign: 'left' as const,
    maxHeight: '60vh',
    overflowY: 'auto' as const,
    boxShadow: '0 0 40px rgba(0,0,0,0.5), inset 0 0 60px rgba(160, 130, 80, 0.2)',
    fontFamily: 'Noto Serif, serif',
    lineHeight: '1.8',
    position: 'relative' as const,
    border: '1px solid #d4af37',
    width: '100%',
    boxSizing: 'border-box' as const,
  },
  toolbar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    background: 'rgba(93, 64, 55, 0.1)',
    padding: '8px 15px',
    borderRadius: '4px',
    marginBottom: '1rem',
    border: '1px solid rgba(138, 110, 47, 0.2)',
  },
  input: {
      display: 'none',
  },
  cardInput: {
      width: '100%',
      padding: '10px',
      marginTop: '5px',
      marginBottom: '15px',
      borderRadius: '4px',
      border: `1px solid ${theme.darkGold}`,
      background: 'rgba(0,0,0,0.3)',
      color: theme.text,
      fontFamily: 'Noto Serif, serif',
      boxSizing: 'border-box' as const,
  },
  formInput: {
      width: '100%',
      padding: '12px',
      borderRadius: '4px',
      border: `1px solid ${theme.darkGold}`,
      background: 'rgba(0,0,0,0.4)',
      color: theme.gold,
      fontSize: '1rem',
      fontFamily: 'Noto Serif, serif',
      marginBottom: '15px',
      boxSizing: 'border-box' as const,
  },
  footer: {
    padding: '2rem 1rem',
    background: 'rgba(5, 5, 17, 0.95)',
    borderTop: `1px solid ${theme.darkGold}`,
    textAlign: 'center' as const,
    color: '#888',
    fontSize: '0.8rem',
    marginTop: 'auto',
  }
};
