
import React, { useEffect, useRef, useState } from 'react';
import { theme, styles } from '../theme';

// ==========================================
// CONFIGURATION - REPLACE WITH YOUR KEYS
// ==========================================
// For PayPal Sandbox, use 'test'. For production, get a Client ID from developer.paypal.com
const PAYPAL_CLIENT_ID = "test"; 

// For Stripe, get your Publishable Key from dashboard.stripe.com
// This is a generic test key provided in Stripe docs for testing.
const STRIPE_PUB_KEY = "pk_test_TYooMQauvdEDq54NiTphI7jx"; 
// ==========================================

declare global {
    interface Window {
        paypal: any;
        Stripe: any;
    }
}

interface PaymentProps {
    amount: number;
    currency: string;
    description: string;
    shippingAddress?: {
        name: string;
        address: string;
        city: string;
        zip: string;
        country: string;
    };
    onSuccess: (details: any) => void;
    onError: (err: any) => void;
    t: any;
}

// --- WECHAT / ALIPAY QR CODE INTEGRATION (Simulated Frontend) ---
// In a real app, your backend would generate the specific qr_code_url from the Weixin/Alipay API
export const QRCodePayment = ({ provider, amount, t, onSuccess }: { provider: 'wechat' | 'alipay', amount: number, t: any, onSuccess: () => void }) => {
    
    useEffect(() => {
        // Simulating a successful payment check polling
        // In a real app, you would poll your backend endpoint here:
        // const interval = setInterval(async () => {
        //    const status = await checkOrderStatus();
        //    if (status === 'paid') onSuccess();
        // }, 2000);
        
        // For this demo, we auto-succeed after a delay to simulate user scanning and paying
        const checkPayment = setTimeout(() => {
            onSuccess();
        }, 5000);

        return () => {
            clearTimeout(checkPayment);
        };
    }, []);

    const color = provider === 'wechat' ? '#2ecc71' : '#3498db';
    const icon = provider === 'wechat' ? 'fa-weixin' : 'fa-alipay';
    const title = provider === 'wechat' ? 'WeChat Pay' : 'Alipay';

    return (
        <div style={{textAlign: 'center', padding: '20px', border: `1px solid ${theme.darkGold}`, borderRadius: '8px', background: 'rgba(255,255,255,0.05)'}}>
            <div style={{fontSize: '1.2rem', color: '#fff', marginBottom: '15px'}}>
                <i className={`fab ${icon}`} style={{color: color, marginRight: '10px'}}></i>
                {title}
            </div>
            
            <div style={{background: '#fff', padding: '10px', display: 'inline-block', borderRadius: '4px'}}>
                {/* Placeholder for Real QR Code generated by backend */}
                <img src={`https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=SimulatedPayment-${provider}-${amount}`} alt="Payment QR" style={{width: '150px', height: '150px'}} />
            </div>
            
            <div style={{marginTop: '15px', color: theme.gold, fontSize: '1.5rem', fontWeight: 'bold'}}>
                ¥{(amount * 7.2).toFixed(2)}
            </div>
            
            <div style={{marginTop: '10px', fontSize: '0.9rem', color: '#aaa'}}>
                {t.scanQRCode || "Please scan to pay"}
            </div>
        </div>
    );
};

// --- PAYPAL INTEGRATION ---
export const PayPalButton = ({ amount, currency, description, onSuccess, onError }: PaymentProps) => {
    const paypalRef = useRef<HTMLDivElement>(null);
    const [sdkReady, setSdkReady] = useState(false);
    const SCRIPT_ID = "paypal-sdk-script-unique"; 

    useEffect(() => {
        // 1. Check if script is already present in DOM
        if (document.getElementById(SCRIPT_ID)) {
            if (window.paypal) {
                setSdkReady(true);
            } else {
                // Wait for existing script to load
                const el = document.getElementById(SCRIPT_ID);
                if (el) el.addEventListener('load', () => setSdkReady(true));
            }
            return;
        }

        // 2. Load the script only if not present
        const script = document.createElement("script");
        script.id = SCRIPT_ID;
        script.src = `https://www.paypal.com/sdk/js?client-id=${PAYPAL_CLIENT_ID}&currency=${currency}&components=buttons`;
        script.type = "text/javascript";
        script.async = true;
        
        script.onload = () => setSdkReady(true);
        script.onerror = () => {
             console.error("PayPal SDK failed to load");
             onError("Failed to load PayPal SDK");
        };
        
        document.body.appendChild(script);
    }, [currency]);

    useEffect(() => {
        if (sdkReady && window.paypal && paypalRef.current) {
            const timer = setTimeout(() => {
                if (!paypalRef.current) return;
                paypalRef.current.innerHTML = ""; 

                try {
                    window.paypal.Buttons({
                        createOrder: (data: any, actions: any) => {
                            return actions.order.create({
                                purchase_units: [{
                                    description: description,
                                    amount: {
                                        value: amount.toString()
                                    }
                                }]
                            });
                        },
                        onApprove: async (data: any, actions: any) => {
                            const order = await actions.order.capture();
                            onSuccess(order);
                        },
                        onError: (err: any) => {
                            console.error("PayPal internal error:", err);
                        }
                    }).render(paypalRef.current).catch((e: any) => {
                        console.error("PayPal button render failed:", e);
                    });
                } catch (err) {
                    console.error("PayPal init exception:", err);
                }
            }, 100);
            return () => clearTimeout(timer);
        }
    }, [sdkReady, amount, description]);

    return (
        <div style={{ marginTop: '20px' }}>
            <div ref={paypalRef} style={{ minHeight: '150px' }}></div>
            {!sdkReady && <div style={{color: '#888', textAlign: 'center'}}>Loading PayPal...</div>}
        </div>
    );
};

// --- STRIPE INTEGRATION ---
export const StripePaymentForm = ({ amount, description, onSuccess, onError, t }: PaymentProps) => {
    const [stripe, setStripe] = useState<any>(null);
    const [elements, setElements] = useState<any>(null);
    const [cardNumber, setCardNumber] = useState<any>(null);
    const [cardExpiry, setCardExpiry] = useState<any>(null);
    const [cardCvc, setCardCvc] = useState<any>(null);
    const [error, setError] = useState<string | null>(null);
    const [processing, setProcessing] = useState(false);
    
    const cardNumberRef = useRef<HTMLDivElement>(null);
    const cardExpiryRef = useRef<HTMLDivElement>(null);
    const cardCvcRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        if (!window.Stripe) {
            setError("Stripe JS not loaded");
            return;
        }
        const stripeInstance = window.Stripe(STRIPE_PUB_KEY);
        setStripe(stripeInstance);
        const elementsInstance = stripeInstance.elements();
        setElements(elementsInstance);

        const style = {
            base: {
                color: '#e0e0e0',
                fontFamily: '"Noto Serif", serif',
                fontSmoothing: 'antialiased',
                fontSize: '16px',
                '::placeholder': { color: '#aab7c4' },
                backgroundColor: 'transparent'
            },
            invalid: { color: '#fa755a', iconColor: '#fa755a' }
        };

        const cardNum = elementsInstance.create('cardNumber', { style, showIcon: true });
        const cardExp = elementsInstance.create('cardExpiry', { style });
        const cardCvcEl = elementsInstance.create('cardCvc', { style });
        
        if(cardNumberRef.current) cardNum.mount(cardNumberRef.current);
        if(cardExpiryRef.current) cardExp.mount(cardExpiryRef.current);
        if(cardCvcRef.current) cardCvcEl.mount(cardCvcRef.current);

        setCardNumber(cardNum);
        setCardExpiry(cardExp);
        setCardCvc(cardCvcEl);

        return () => {
             cardNum.destroy();
             cardExp.destroy();
             cardCvcEl.destroy();
        };
    }, []);

    const handleSubmit = async (event: React.FormEvent) => {
        event.preventDefault();
        setProcessing(true);

        if (!stripe || !cardNumber || !cardExpiry || !cardCvc) {
            setProcessing(false);
            return;
        }

        const result = await stripe.createPaymentMethod({
            type: 'card',
            card: cardNumber, 
            billing_details: { name: 'Mystic Face Customer' },
        });

        if (result.error) {
            setError(result.error.message);
            setProcessing(false);
            onError(result.error);
        } else {
            setTimeout(() => {
                 setProcessing(false);
                 onSuccess(result);
            }, 1000);
        }
    };

    const containerStyle = {
        padding: '10px 12px', 
        border: `1px solid ${theme.darkGold}`, 
        borderRadius: '4px',
        background: 'rgba(0,0,0,0.3)',
        marginBottom: '15px'
    };

    return (
        <form onSubmit={handleSubmit} style={{marginTop: '20px'}}>
            <div style={{marginBottom: '5px'}}>
                <label style={{display: 'block', color: '#aaa', marginBottom: '5px', fontSize: '0.8rem'}}>{t.cardNumber}</label>
                <div ref={cardNumberRef} style={containerStyle}></div>
            </div>
            <div style={{display: 'flex', gap: '15px'}}>
                <div style={{flex: 1}}>
                    <label style={{display: 'block', color: '#aaa', marginBottom: '5px', fontSize: '0.8rem'}}>{t.expiry}</label>
                    <div ref={cardExpiryRef} style={containerStyle}></div>
                </div>
                <div style={{flex: 1}}>
                    <label style={{display: 'block', color: '#aaa', marginBottom: '5px', fontSize: '0.8rem'}}>{t.cvc}</label>
                    <div ref={cardCvcRef} style={containerStyle}></div>
                </div>
            </div>
            {error && <div style={{color: '#fa755a', fontSize: '0.9rem', marginBottom: '15px'}}>{error}</div>}
            <button type="submit" disabled={!stripe || processing} style={{...styles.button, width: '100%', opacity: processing ? 0.7 : 1, cursor: processing ? 'not-allowed' : 'pointer'}}>
                {processing ? t.processing : `${t.payNow} ($${amount})`}
            </button>
            <div style={{marginTop:'10px', fontSize:'0.7rem', color:'#666', textAlign:'center'}}>
                <i className="fas fa-lock"></i> {t.secureStripe || "Secured by Stripe"}
            </div>
        </form>
    );
};
